markdown: redcarpet
baseurl: /interaction-collection
exclude: ['README.md']
tag_permalink_style: pretty
tag_page_data:
  sitemap: false
ignored_tags: [tags,to,ignore]
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
