markdown: kramdown

exclude: ['README.md']

# Permalinks
permalink:        pretty

# Setup
# title:            interaction-collection
# url:              http://jensschnitzler.com
# baseurl:          /interaction-collection
# author:
#   name:           Jens Schnitzler
#   email:          jens.schnitzler@gmail.com


collections:
  - poetry:
      output: true
  - my_categories:
      output: true
      #permalink: /blog/category/:name/
  - my_tags:
      output: true
      #permalink: /blog/tag/:name/
